using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HealthNetParser.Model
{
	public class HSPReadyNewMember
	{
		public class HSPReadyModel
		{
			public string GroupNumber { get; set; }
			public string NationalIndividualID { get; set; }
			public string SubscriberNumber { get; set; }
			public string SubscriberPolicyNumber { get; set; }
			public string SubscriberSSN { get; set; }
			public string MemberNumber { get; set; }
			public string MemberPolicyNumber { get; set; }
			public string SocialSecurityNumber { get; set; }
			public string TierName { get; set; }
			public string TierCode { get; set; }
			public string LastName { get; set; }
			public string FirstName { get; set; }
			public string MiddleName { get; set; }
			public string Address1 { get; set; }
			public string Address2 { get; set; }
			public string City { get; set; }
			public string State { get; set; }
			public string Zip { get; set; }
			public string County { get; set; }
			public string CountryCode { get; set; }
			public string Latitude { get; set; }
			public string Longitude { get; set; }
			public string LocationCode { get; set; }
			public string HomePhone { get; set; }
			public string WorkPhone { get; set; }
			public string CellPhone { get; set; }
			public string Gender { get; set; }
			public string DateOfBirth { get; set; }
			public string DateOfDeath { get; set; }
			public string RelationshipCode { get; set; }
			public string ProviderNumber { get; set; }
			public string ProviderNumberQualifier { get; set; }
			public string PCPPrecedence { get; set; }
			public string ManuallyAssigned { get; set; }
			public string OverrideEffectiveDate { get; set; }
			public string OverrideTerminationDate { get; set; }
			public string OverrideRetroEnrollmentEnforcement { get; set; }
			public string OverrideTierRestrictions { get; set; }
			public string TierUpdate { get; set; }
			public string TierUpdateAsOfDate { get; set; }
			public string EffectiveDate { get; set; }
			public string ExpirationDate { get; set; }
			public string PrimaryInsurance { get; set; }
			public string NamePrefix { get; set; }
			public string NameSuffix { get; set; }
			public string NameFormat { get; set; }
			public string Email { get; set; }
			public string MaritalStatus { get; set; }
			public string EmployerName { get; set; }
			public string DependentViewWebOption { get; set; }
			public string TerminationDate { get; set; }
			public string TerminationReason { get; set; }
			public string MaintenanceReasonCode { get; set; }
			public string MaintenanceTypeCode { get; set; }
			public string ProviderOrganization { get; set; }
			public string PrimarySecondaryIndicator { get; set; }
			public string ProviderNetworkName { get; set; }
			public string NetworkEffectiveDate { get; set; }
			public string NetworkExpirationDate { get; set; }
			public string ActiveMemberSince { get; set; }
			public string LastNameMatch { get; set; }
			public string Ethnicity { get; set; }
			public string OfficeAddress1 { get; set; }
			public string OfficeZip { get; set; }
			public string OfficeNumber { get; set; }
			public string RiskGroupNumber { get; set; }
			public string HospitalNumber { get; set; }
			public string PrimaryLanguage { get; set; }
			public string COBPrecedence { get; set; }
			public string COBPayerName { get; set; }
			public string COBPayerType { get; set; }
			public string COBPayerNumber { get; set; }
			public string COBPayerNumberQualifier { get; set; }
			public string COBCoverage { get; set; }
			public string COBEffectiveDate { get; set; }
			public string COBExpirationDate { get; set; }
			public string UseMemberAddress { get; set; }
			public string UseAnyTier { get; set; }
			public string SaveAltAddress { get; set; }
			public string AlternateAddressType { get; set; }
			public string TermExistBenefitsBeforeAddNew { get; set; }
			public string AutoAssignPCP { get; set; }
			public string AutoAssignProviderFromOffice { get; set; }
			public string UpdateIdentifyingElements { get; set; }
			public string UpdatePolicyNumber { get; set; }
			public string UpdateSSN { get; set; }
			public string UpdateName { get; set; }
			public string UpdateDateOfBirth { get; set; }
			public string UpdateActiveMemberSince { get; set; }
			public string UpdateAdditionalInformation { get; set; }
			public string UpdateNationalIndividualID { get; set; }
			public string UpdateAdditionalNameDetails { get; set; }
			public string UpdateStreetAddressInfo { get; set; }
			public string UpdateMainAddressInfo { get; set; }
			public string UpdateLocationCode { get; set; }
			public string UpdateContactInfo { get; set; }
			public string UpdateGender { get; set; }
			public string UpdateDateOfDeath { get; set; }
			public string UpdateEthnicity { get; set; }
			public string UpdateMaritalStatus { get; set; }
			public string UpdateHICN { get; set; }
			public string UpdateMemberEOBFulfillment { get; set; }
			public string UpdateMemberNumberFlag { get; set; }
			public string OverridePCPPanel { get; set; }
			public string OldMemberNumber { get; set; }
			public string OldDateOfBirth { get; set; }
			public string OldLastName { get; set; }
			public string OldFirstName { get; set; }
			public string OldSSN { get; set; }
			public string OldAddress1 { get; set; }
			public string OldCity { get; set; }
			public string OldState { get; set; }
			public string OldZip { get; set; }
			public string OverrideMismatch { get; set; }
			public string OverrideDupMemberNumber { get; set; }
			public string AutoGenerateCityAndState { get; set; }
			public string CustomAttributes { get; set; }
			public string MemberCoverageAttributes { get; set; }
			public string ResponsiblePartyLastName { get; set; }
			public string ResponsiblePartyFirstName { get; set; }
			public string ResponsiblePartySuffix { get; set; }
			public string ResponsiblePartyMiddleName { get; set; }
			public string ResponsiblePartyType { get; set; }
			public string ResponsiblePartyNII { get; set; }
			public string ResponsiblePartySSN { get; set; }
			public string ResponsiblePartyNumber { get; set; }
			public string ResponsiblePartyDOB { get; set; }
			public string ResponsiblePartyRelationshipCode { get; set; }
			public string ResponsiblePartyGender { get; set; }
			public string ResponsiblePartyGroupNumber { get; set; }
			public string ResponsiblePartyAddress { get; set; }
			public string ResponsiblePartyAddress2 { get; set; }
			public string ResponsiblePartyCity { get; set; }
			public string ResponsiblePartyState { get; set; }
			public string ResponsiblePartyZip { get; set; }
			public string ResponsiblePartyLocationCode { get; set; }
			public string ResponsiblePartyHomePhone { get; set; }
			public string ResponsiblePartyWorkPhone { get; set; }
			public string ResponsiblePartyCellPhone { get; set; }
			public string ResponsiblePartyEmail { get; set; }
			public string ResponsiblePartyAlternateAddressType { get; set; }
			public string ResponsiblePartyMailingAddress { get; set; }
			public string ResponsiblePartyMailingAddress2 { get; set; }
			public string ResponsiblePartyMailingCity { get; set; }
			public string ResponsiblePartyMailingState { get; set; }
			public string ResponsiblePartyMailingZip { get; set; }
			public string ResponsiblePartyCustomAttributes { get; set; }
			public string ResponsibleEffectiveDate { get; set; }
			public string ResponsibleExpirationDate { get; set; }
			public string SeparateOutOfNetworkIDCard { get; set; }
			public string OverrideMultipleResponsibleParties { get; set; }
			public string HouseholdReferenceNumber { get; set; }
			public string CreateNewHousehold { get; set; }
			public string InheritResponsibleParty { get; set; }
			public string AddNewMemberPCPMapSlice { get; set; }
			public string Volume { get; set; }
			public string HireDate { get; set; }
			public string HICN { get; set; }
			public string MedicareEntitlementReason { get; set; }
			public string MemberToPayNumber { get; set; }
			public string MemberToPayGroupNumber { get; set; }
			public string DisallowNewMembers { get; set; }
			public string MemberEOBFulfillment { get; set; }
			public string Source834XMLID { get; set; }
			public string AidCodesXML { get; set; }
			public string LanguagesXML { get; set; }
			public string PlanCoverageDescription { get; set; }
			public string BenefitCode { get; set; }
			public string StatusCode { get; set; }
			public string SOCStatus { get; set; }
			public string SOCAmount { get; set; }
			public string SOCCertDate { get; set; }
			public string MCDEffectiveDate { get; set; }
			public string MCDExpirationDate { get; set; }
			public string ExternalRowID { get; set; }
			public string UpdateMemberToPay { get; set; }
			public string ContactReasonShortcut { get; set; }
			public string CreateCOBPayerFlag { get; set; }
			public string MBI { get; set; }
			public string UpdateMBI { get; set; }
		}

	}
}
